### create article
POST http://localhost:8080/article/moderator/create
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTgzODI4MDIsImlkIjo3LCJ1c2VybmFtZSI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxODQ2OTIwMiwiaXNzIjoiS3VuVXoifQ.VR1sMa0CX7uu1GULviqtc6rO02bL-KbUFVodLQP1NEnvtqSHjh9lLMOn048RJ3mtBHV2s5ulrftf6-qdrpXk4Q

{
  "title": "title",
  "description": "description",
  "content": "content",
  "imageId": 1,
  "regionId": 1,
  "categoryId": 1,
  "types": [1]
}
