### Create types
POST localhost:8080/types/admin/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTgzODE2MDYsImlkIjoxLCJ1c2VybmFtZSI6Im1hemdpaUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxODQ2ODAwNiwiaXNzIjoiS3VuVXoifQ.Vv5G_U0o87ykw2SPH6qiQzx08jTfenvMc1Rd6xJ6TNo5MWtFCqWNnYfc7klS2QiCp7aVXLo7CX1ty5U6sICtQw

{
  "orderNumber": 2,
  "nameUz": "type uz",
  "nameEn": "type en",
  "nameRu": "type ru"
}
### Get all
GET localhost:8080/types/admin/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc0MjM3OTIsImlkIjoxLCJ1c2VybmFtZSI6Im1hemdpaUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxNzUxMDE5MiwiaXNzIjoiS3VuVXoifQ.Lk4oN-1bxPyKsPQhRNmKPJXf0tSwUR-_d8ihOdGGCl71g0Zs_6O-KkJHtS5qtmP4WlNMmf6Wvw5oMukC7y8p_w"

### Get all by lang
GET localhost:8080/types/lang
Accept-Language: EN

### update
PUT localhost:8080/types/admin/update/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc0MjM3OTIsImlkIjoxLCJ1c2VybmFtZSI6Im1hemdpaUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxNzUxMDE5MiwiaXNzIjoiS3VuVXoifQ.Lk4oN-1bxPyKsPQhRNmKPJXf0tSwUR-_d8ihOdGGCl71g0Zs_6O-KkJHtS5qtmP4WlNMmf6Wvw5oMukC7y8p_w"

{
  "orderNumber": 2,
  "nameUz": "type uz",
  "nameEn": "type en",
  "nameRu": "type ru"
}

### delete by id
DELETE localhost:8080/types/admin/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc0MjM3OTIsImlkIjoxLCJ1c2VybmFtZSI6Im1hemdpaUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxNzUxMDE5MiwiaXNzIjoiS3VuVXoifQ.Lk4oN-1bxPyKsPQhRNmKPJXf0tSwUR-_d8ihOdGGCl71g0Zs_6O-KkJHtS5qtmP4WlNMmf6Wvw5oMukC7y8p_w"