### Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Takhir",
  "surname": "Ismailov",
  "email": "takhir.4ismailoff@gmail.com",
  "password": "12345"
}

### login
POST localhost:8080/auth/login?email=takhir.ismailoff@gmail.com&password=12345

