### Registration with phone
POST localhost:8080/auth/registrationWithPhone
Content-Type: application/json

{
  "name": "Alish",
  "surname": "aliyev",
  "email": "takhir@gmail.com",
  "phone": "998946386808",
  "password": "12345"
}
### Registration with email
POST localhost:8080/auth/registrationWithEmail
Content-Type: application/json

{
  "name": "test",
  "surname": "test",
  "email": "test@gmail.com",
  "phone": "998946086828",
  "password": "12345"
}

### resend sms
GET localhost:8080/auth/registration/resendSms/998946486808

### resend email
GET localhost:8080/auth/registration/resendEmail/takhir.ismailoff@gmail.com

### verification with phone
POST localhost:8080/auth/verificationWithSms
Content-Type: application/json

{
    "phone": "998946486808",
    "message": "72855"
}


### login with email
POST localhost:8080/auth/loginWithEmail
Content-Type: application/json

{
  "email": "mazgii@gmail.com",
  "password": "12345"
}

### login with phone
POST localhost:8080/auth/loginWithPhone
Content-Type: application/json

{
  "phone": "998946386808",
  "password": "12345"
}
