### get by email
GET http://localhost:8080/email/byEmail?email=takhir.ismailoff@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc0Mzg4MDksImlkIjozLCJ1c2VybmFtZSI6InRlc3QxQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MTc1MjUyMDksImlzcyI6Ikt1blV6In0.EGDkQ2_x2kQtB3uEXNWfH3oIfUH2B42Moh-z8LuB2Zbbt3acVBvS9JqoKMtNzGutboNyU8XVNaEFLgiCjdsTkA"

### get by given date
GET http://localhost:8080/email/givenDate?date=2024-05-23
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc0Mzg4MDksImlkIjozLCJ1c2VybmFtZSI6InRlc3QxQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MTc1MjUyMDksImlzcyI6Ikt1blV6In0.EGDkQ2_x2kQtB3uEXNWfH3oIfUH2B42Moh-z8LuB2Zbbt3acVBvS9JqoKMtNzGutboNyU8XVNaEFLgiCjdsTkA"

### pagination
GET http://localhost:8080/email/admin/pagination?pageNumber=1&pageSize=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc0MjM0OTMsImlkIjoxLCJ1c2VybmFtZSI6Im1hemdpaUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxNzUwOTg5MywiaXNzIjoiS3VuVXoifQ.8xkZlZpbEvvLTuI1ipbNc0yNJTdVqdORiKavPC6B-gqE2uldT0z7yZYxwKM9I1gSienyozQ1tvVvExusXe_nLQ"